import UserLayout from "@/layouts/user-layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sound Board",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <UserLayout>{children}</UserLayout>;
}
